language: python

python:
    - "3.4"
    - "3.5"

install:
    - pip install -U pip
    - pip install .[test,dev]

script: 
    - python setup.py test
    - pylint simple_wbd tests

after_success:
    - codecov
